#AWS working on this port
server:
  port: 8080

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_NAME}

kafka:
  server: 35.195.168.206:9092

management:
  health:
    diskspace:
      enabled: false
      