bot:
  token: ${BOT_TOKEN}
  username: ${BOT_NAME}

management:
  health:
    diskspace:
      enabled: false

spring:
  sleuth:
    sampler:
      probability: 1.0
    web:
      additional-skip-pattern: "(^cleanup.*|.+favicon.*)"
  profiles:
    active: ${ACTIVE_PROFILE}

server:
  port: 8081
