server:
  port: 8080

mongodb:
  database: "mydb"
  collection: "message"
  uri: "mongodb://34.78.196.126:27017"

spring:
  kafka:
    bootstrap-servers: 35.195.168.206:9092

management:
  health:
    diskspace:
      enabled: false
